// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dsw1_t1_Alburqueque_Jose.Data;

#nullable disable

namespace DSW1_T1_Alburqueque_Jose.Migrations
{
    [DbContext(typeof(AplicationsContext))]
    [Migration("20251126031738_initialCreate")]
    partial class initialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("dsw1_t1_Alburqueque_Jose.Models.Curso", b =>
                {
                    b.Property<int>("CursoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("cursoId");

                    b.Property<string>("CodigoCurso")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("codigoCurso");

                    b.Property<int>("Creditos")
                        .HasColumnType("int")
                        .HasColumnName("creditos");

                    b.Property<int>("HorasSemanales")
                        .HasColumnType("int")
                        .HasColumnName("horasSemanales");

                    b.Property<int>("NivelAcademicoId")
                        .HasColumnType("int")
                        .HasColumnName("nivelAcademicoId");

                    b.Property<string>("NombreCurso")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("nombreCurso");

                    b.HasKey("CursoId");

                    b.HasIndex("NivelAcademicoId");

                    b.ToTable("cursos");
                });

            modelBuilder.Entity("dsw1_t1_Alburqueque_Jose.Models.NivelAcademico", b =>
                {
                    b.Property<int>("NivelAcademicoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("nivelAcademicoId");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("descripcion");

                    b.Property<int>("Orden")
                        .HasColumnType("int")
                        .HasColumnName("orden");

                    b.HasKey("NivelAcademicoId");

                    b.ToTable("nivelAcademico");
                });

            modelBuilder.Entity("dsw1_t1_Alburqueque_Jose.Models.Curso", b =>
                {
                    b.HasOne("dsw1_t1_Alburqueque_Jose.Models.NivelAcademico", "NivelAcademico")
                        .WithMany("Cursos")
                        .HasForeignKey("NivelAcademicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NivelAcademico");
                });

            modelBuilder.Entity("dsw1_t1_Alburqueque_Jose.Models.NivelAcademico", b =>
                {
                    b.Navigation("Cursos");
                });
#pragma warning restore 612, 618
        }
    }
}
